name: Node.js CI with Jest

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]


jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: local_tes_password
          POSTGRES_DB: my_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 1s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        code-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Jest Test Suite
      run: npm test
      env:
        DATABASE_URL: postgres://postgres:local_test_password@localhost:5432/my_test_db
        JWT_SECRET: ci_testing_one_secret_key
        NODE_ENV: test